// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_cloud::schema::lib::Input as OrdinaryInput;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::Output as OrdinaryOutput;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Input as MetaInput;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Output as MetaOutput;
#[rustfmt::skip]
pub use crate::schema::sema::SemaReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::SemaReadOutput as SemaReadOutput;
#[rustfmt::skip]
pub use crate::schema::sema::SemaWriteInput as SemaWriteInput;
#[rustfmt::skip]
pub use crate::schema::sema::SemaWriteOutput as SemaWriteOutput;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::ZoneQuery as ZoneQuery;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::RecordQuery as RecordQuery;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::ZoneListing as ZoneListing;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::RecordListing as RecordListing;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::PlanIdentifier as PlanIdentifier;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::PlanApplied as PlanApplied;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalArrived(SignalInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadCompleted(SemaReadOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaWriteCompleted(SemaWriteOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectCompleted(EffectResult);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaRead(SemaReadInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaWrite(SemaWriteInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandEffect(EffectCommand);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReplyToSignal(SignalOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Continue(NexusWork);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalInput {
    OrdinaryInput(OrdinaryInput),
    MetaInput(MetaInput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalOutput {
    OrdinaryOutput(OrdinaryOutput),
    MetaOutput(MetaOutput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectCommand {
    CloudflareObserveZones(CloudflareObserveZones),
    CloudflareObserveRecords(CloudflareObserveRecords),
    CloudflareApplyPlan(CloudflareApplyPlan),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CloudflareObserveZones(ZoneQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CloudflareObserveRecords(RecordQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CloudflareApplyPlan(PlanIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectResult {
    ZonesObserved(ZonesObserved),
    RecordsObserved(RecordsObserved),
    PlanApplied(PlanApplied),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ZonesObserved(ZoneListing);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordsObserved(RecordListing);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    SemaReadCompleted(SemaReadCompleted),
    SemaWriteCompleted(SemaWriteCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    CommandSemaRead(CommandSemaRead),
    CommandSemaWrite(CommandSemaWrite),
    CommandEffect(CommandEffect),
    ReplyToSignal(ReplyToSignal),
    Continue(Continue),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    NexusWork(NexusWork),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    NexusAction(NexusAction),
}

#[rustfmt::skip]
impl SignalArrived {
    pub fn new(payload: SignalInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalInput {
        &self.0
    }
    pub fn into_payload(self) -> SignalInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalInput> for SignalArrived {
    fn from(payload: SignalInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadCompleted {
    pub fn new(payload: SemaReadOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadOutput> for SemaReadCompleted {
    fn from(payload: SemaReadOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteCompleted {
    pub fn new(payload: SemaWriteOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteOutput> for SemaWriteCompleted {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EffectCompleted {
    pub fn new(payload: EffectResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EffectResult {
        &self.0
    }
    pub fn into_payload(self) -> EffectResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<EffectResult> for EffectCompleted {
    fn from(payload: EffectResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaRead {
    pub fn new(payload: SemaReadInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadInput> for CommandSemaRead {
    fn from(payload: SemaReadInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaWrite {
    pub fn new(payload: SemaWriteInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteInput> for CommandSemaWrite {
    fn from(payload: SemaWriteInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandEffect {
    pub fn new(payload: EffectCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EffectCommand {
        &self.0
    }
    pub fn into_payload(self) -> EffectCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<EffectCommand> for CommandEffect {
    fn from(payload: EffectCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReplyToSignal {
    pub fn new(payload: SignalOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalOutput {
        &self.0
    }
    pub fn into_payload(self) -> SignalOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalOutput> for ReplyToSignal {
    fn from(payload: SignalOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Continue {
    pub fn new(payload: NexusWork) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusWork {
        &self.0
    }
    pub fn into_payload(self) -> NexusWork {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusWork> for Continue {
    fn from(payload: NexusWork) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CloudflareObserveZones {
    pub fn new(payload: ZoneQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ZoneQuery {
        &self.0
    }
    pub fn into_payload(self) -> ZoneQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<ZoneQuery> for CloudflareObserveZones {
    fn from(payload: ZoneQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CloudflareObserveRecords {
    pub fn new(payload: RecordQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordQuery {
        &self.0
    }
    pub fn into_payload(self) -> RecordQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordQuery> for CloudflareObserveRecords {
    fn from(payload: RecordQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CloudflareApplyPlan {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanIdentifier> for CloudflareApplyPlan {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ZonesObserved {
    pub fn new(payload: ZoneListing) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ZoneListing {
        &self.0
    }
    pub fn into_payload(self) -> ZoneListing {
        self.0
    }
}
#[rustfmt::skip]
impl From<ZoneListing> for ZonesObserved {
    fn from(payload: ZoneListing) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordsObserved {
    pub fn new(payload: RecordListing) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordListing {
        &self.0
    }
    pub fn into_payload(self) -> RecordListing {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordListing> for RecordsObserved {
    fn from(payload: RecordListing) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SignalInput {
    pub fn ordinary_input(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }
    pub fn meta_input(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

#[rustfmt::skip]
impl SignalOutput {
    pub fn ordinary_output(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }
    pub fn meta_output(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

#[rustfmt::skip]
impl EffectCommand {
    pub fn cloudflare_observe_zones(payload: ZoneQuery) -> Self {
        Self::CloudflareObserveZones(CloudflareObserveZones::new(payload))
    }
    pub fn cloudflare_observe_records(payload: RecordQuery) -> Self {
        Self::CloudflareObserveRecords(CloudflareObserveRecords::new(payload))
    }
    pub fn cloudflare_apply_plan(payload: PlanIdentifier) -> Self {
        Self::CloudflareApplyPlan(CloudflareApplyPlan::new(payload))
    }
}

#[rustfmt::skip]
impl EffectResult {
    pub fn zones_observed(payload: ZoneListing) -> Self {
        Self::ZonesObserved(ZonesObserved::new(payload))
    }
    pub fn records_observed(payload: RecordListing) -> Self {
        Self::RecordsObserved(RecordsObserved::new(payload))
    }
    pub fn plan_applied(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn effect_completed(payload: EffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn command_effect(payload: EffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn nexus_work(payload: NexusWork) -> Self {
        Self::NexusWork(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn nexus_action(payload: NexusAction) -> Self {
        Self::NexusAction(payload)
    }
}

#[rustfmt::skip]
impl From<OrdinaryInput> for SignalInput {
    fn from(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }
}

#[rustfmt::skip]
impl From<MetaInput> for SignalInput {
    fn from(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

#[rustfmt::skip]
impl From<OrdinaryOutput> for SignalOutput {
    fn from(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }
}

#[rustfmt::skip]
impl From<MetaOutput> for SignalOutput {
    fn from(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

#[rustfmt::skip]
impl From<CloudflareObserveZones> for EffectCommand {
    fn from(payload: CloudflareObserveZones) -> Self {
        Self::CloudflareObserveZones(payload)
    }
}

#[rustfmt::skip]
impl From<CloudflareObserveRecords> for EffectCommand {
    fn from(payload: CloudflareObserveRecords) -> Self {
        Self::CloudflareObserveRecords(payload)
    }
}

#[rustfmt::skip]
impl From<CloudflareApplyPlan> for EffectCommand {
    fn from(payload: CloudflareApplyPlan) -> Self {
        Self::CloudflareApplyPlan(payload)
    }
}

#[rustfmt::skip]
impl From<ZonesObserved> for EffectResult {
    fn from(payload: ZonesObserved) -> Self {
        Self::ZonesObserved(payload)
    }
}

#[rustfmt::skip]
impl From<RecordsObserved> for EffectResult {
    fn from(payload: RecordsObserved) -> Self {
        Self::RecordsObserved(payload)
    }
}

#[rustfmt::skip]
impl From<PlanApplied> for EffectResult {
    fn from(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for NexusWork {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for NexusWork {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for NexusWork {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for NexusWork {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for NexusAction {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for NexusAction {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for NexusAction {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for NexusAction {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for NexusAction {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<NexusWork> for Input {
    fn from(payload: NexusWork) -> Self {
        Self::NexusWork(payload)
    }
}

#[rustfmt::skip]
impl From<NexusAction> for Output {
    fn from(payload: NexusAction) -> Self {
        Self::NexusAction(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaReadCompleted,
    SemaWriteCompleted,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    CommandSemaRead,
    CommandSemaWrite,
    CommandEffect,
    ReplyToSignal,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_ {
        async move {
            self.trace_nexus_entered();
            let output = self.decide(input);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
