// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_cloud::schema::lib::Input as OrdinaryInput;
pub use signal_cloud::schema::lib::Output as OrdinaryOutput;
pub use meta_signal_cloud::schema::lib::Input as MetaInput;
pub use meta_signal_cloud::schema::lib::Output as MetaOutput;
pub use cloud::schema::sema::SemaReadInput as SemaReadInput;
pub use cloud::schema::sema::SemaReadOutput as SemaReadOutput;
pub use cloud::schema::sema::SemaWriteInput as SemaWriteInput;
pub use cloud::schema::sema::SemaWriteOutput as SemaWriteOutput;
pub use signal_cloud::schema::lib::ZoneQuery as ZoneQuery;
pub use signal_cloud::schema::lib::RecordQuery as RecordQuery;
pub use signal_cloud::schema::lib::ZoneListing as ZoneListing;
pub use signal_cloud::schema::lib::RecordListing as RecordListing;
pub use meta_signal_cloud::schema::lib::PlanIdentifier as PlanIdentifier;
pub use meta_signal_cloud::schema::lib::PlanApplied as PlanApplied;

pub type SignalArrived = SignalInput;

pub type SemaReadCompleted = SemaReadOutput;

pub type SemaWriteCompleted = SemaWriteOutput;

pub type EffectCompleted = EffectResult;

pub type CommandSemaRead = SemaReadInput;

pub type CommandSemaWrite = SemaWriteInput;

pub type CommandEffect = EffectCommand;

pub type ReplyToSignal = SignalOutput;

pub type Continue = NexusWork;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalInput {
    OrdinaryInput(OrdinaryInput),
    MetaInput(MetaInput),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalOutput {
    OrdinaryOutput(OrdinaryOutput),
    MetaOutput(MetaOutput),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectCommand {
    CloudflareObserveZones(CloudflareObserveZones),
    CloudflareObserveRecords(CloudflareObserveRecords),
    CloudflareApplyPlan(CloudflareApplyPlan),
}

pub type CloudflareObserveZones = ZoneQuery;

pub type CloudflareObserveRecords = RecordQuery;

pub type CloudflareApplyPlan = PlanIdentifier;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectResult {
    ZonesObserved(ZonesObserved),
    RecordsObserved(RecordsObserved),
    PlanApplied(PlanApplied),
}

pub type ZonesObserved = ZoneListing;

pub type RecordsObserved = RecordListing;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    SemaReadCompleted(SemaReadCompleted),
    SemaWriteCompleted(SemaWriteCompleted),
    EffectCompleted(EffectCompleted),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    CommandSemaRead(CommandSemaRead),
    CommandSemaWrite(CommandSemaWrite),
    CommandEffect(CommandEffect),
    ReplyToSignal(ReplyToSignal),
    Continue(Continue),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    NexusWork(NexusWork),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    NexusAction(NexusAction),
}

impl SignalInput {
    pub fn ordinary_input(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }

    pub fn meta_input(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

impl SignalOutput {
    pub fn ordinary_output(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }

    pub fn meta_output(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

impl EffectCommand {
    pub fn cloudflare_observe_zones(payload: CloudflareObserveZones) -> Self {
        Self::CloudflareObserveZones(payload)
    }

    pub fn cloudflare_observe_records(payload: CloudflareObserveRecords) -> Self {
        Self::CloudflareObserveRecords(payload)
    }

    pub fn cloudflare_apply_plan(payload: CloudflareApplyPlan) -> Self {
        Self::CloudflareApplyPlan(payload)
    }
}

impl EffectResult {
    pub fn zones_observed(payload: ZonesObserved) -> Self {
        Self::ZonesObserved(payload)
    }

    pub fn records_observed(payload: RecordsObserved) -> Self {
        Self::RecordsObserved(payload)
    }

    pub fn plan_applied(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

impl NexusWork {
    pub fn signal_arrived(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }

    pub fn sema_read_completed(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }

    pub fn sema_write_completed(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }

    pub fn effect_completed(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

impl NexusAction {
    pub fn command_sema_read(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }

    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }

    pub fn command_effect(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }

    pub fn reply_to_signal(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }

    pub fn r#continue(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

impl Input {
    pub fn nexus_work(payload: NexusWork) -> Self {
        Self::NexusWork(payload)
    }
}

impl Output {
    pub fn nexus_action(payload: NexusAction) -> Self {
        Self::NexusAction(payload)
    }
}

impl From<OrdinaryInput> for SignalInput {
    fn from(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }
}

impl From<MetaInput> for SignalInput {
    fn from(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

impl From<OrdinaryOutput> for SignalOutput {
    fn from(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }
}

impl From<MetaOutput> for SignalOutput {
    fn from(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

impl From<PlanApplied> for EffectResult {
    fn from(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

impl From<NexusWork> for Input {
    fn from(payload: NexusWork) -> Self {
        Self::NexusWork(payload)
    }
}

impl From<NexusAction> for Output {
    fn from(payload: NexusAction) -> Self {
        Self::NexusAction(payload)
    }
}



pub mod short_header {
    pub const INPUT_NEXUS_WORK: u64 = 0x0000000000000000;
    pub const OUTPUT_NEXUS_ACTION: u64 = 0x0100000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    NexusWork,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    NexusAction,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::NexusWork(_) => InputRoute::NexusWork,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::NexusWork(_) => short_header::INPUT_NEXUS_WORK,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_NEXUS_WORK => Ok(InputRoute::NexusWork),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::NexusAction(_) => OutputRoute::NexusAction,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::NexusAction(_) => short_header::OUTPUT_NEXUS_ACTION,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_NEXUS_ACTION => Ok(OutputRoute::NexusAction),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaReadCompleted,
    SemaWriteCompleted,
    EffectCompleted,
}

impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusActionRoute {
    CommandSemaRead,
    CommandSemaWrite,
    CommandEffect,
    ReplyToSignal,
    Continue,
}

impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}

impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => match route {
                NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
            },
            Self::Action(route) => match route {
                NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                NexusActionRoute::Continue => "NexusActionContinue",
            },
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct TraceEvent(pub ObjectName);

impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}

impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }

    pub fn object_name(&self) -> ObjectName {
        self.0
    }

    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}

impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => write!(formatter, "actor resource busy: {message}"),
            Self::ConfigurationInvalid(message) => write!(formatter, "actor configuration invalid: {message}"),
        }
    }
}

impl std::error::Error for ActorStartFailure {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}

impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => write!(formatter, "actor resource locked: {message}"),
            Self::ChildStillRunning(message) => write!(formatter, "actor child still running: {message}"),
        }
    }
}

impl std::error::Error for ActorStopFailure {}

pub trait NexusEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }

    fn decide(&mut self, input: nexus::Nexus<nexus::Work>) -> nexus::Nexus<nexus::Action>;

    fn execute(&mut self, input: nexus::Nexus<nexus::Work>) -> nexus::Nexus<nexus::Action> {
        self.trace_nexus_entered();
        let output = self.decide(input);
        self.trace_nexus_decided();
        output
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
