// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_cloud::schema::lib::Observation as Observation;
pub use signal_cloud::schema::lib::PlanQuery as PlanQuery;
pub use signal_cloud::schema::lib::Validation as Validation;
pub use signal_cloud::schema::lib::Observed as Observed;
pub use signal_cloud::schema::lib::Validated as Validated;
pub use signal_cloud::schema::lib::PlanResult as PlanResult;
pub use meta_signal_cloud::schema::lib::Registration as Registration;
pub use meta_signal_cloud::schema::lib::Rotation as Rotation;
pub use meta_signal_cloud::schema::lib::Policy as Policy;
pub use meta_signal_cloud::schema::lib::PlanPreparation as PlanPreparation;
pub use meta_signal_cloud::schema::lib::ProjectionPreparation as ProjectionPreparation;
pub use meta_signal_cloud::schema::lib::Approval as Approval;
pub use meta_signal_cloud::schema::lib::Application as Application;
pub use meta_signal_cloud::schema::lib::Retirement as Retirement;
pub use meta_signal_cloud::schema::lib::AccountRegistered as AccountRegistered;
pub use meta_signal_cloud::schema::lib::CredentialRotated as CredentialRotated;
pub use meta_signal_cloud::schema::lib::PolicySet as PolicySet;
pub use meta_signal_cloud::schema::lib::PlanPrepared as PlanPrepared;
pub use meta_signal_cloud::schema::lib::PlanApproved as PlanApproved;
pub use meta_signal_cloud::schema::lib::PlanApplied as PlanApplied;
pub use meta_signal_cloud::schema::lib::AccountRetired as AccountRetired;
pub use meta_signal_cloud::schema::lib::RequestRejected as RequestRejected;
pub use meta_signal_cloud::schema::lib::Plan as Plan;
pub use signal_cloud::schema::lib::Provider as Provider;
pub use signal_cloud::schema::lib::ProviderAccount as ProviderAccount;
pub use meta_signal_cloud::schema::lib::CredentialHandle as CredentialHandle;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    Observe(Observe),
    ObservePlan(ObservePlan),
    Validate(Validate),
}

pub type Observe = Observation;

pub type ObservePlan = PlanQuery;

pub type Validate = Validation;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    Observed(Observed),
    Validated(Validated),
    PlanObserved(PlanObserved),
    Missed(Missed),
}

pub type PlanObserved = PlanResult;

pub type Missed = RejectionReport;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    RegisterAccount(RegisterAccount),
    RotateCredential(RotateCredential),
    SetPolicy(SetPolicy),
    PreparePlan(PreparePlan),
    PrepareProjection(PrepareProjection),
    ApprovePlan(ApprovePlan),
    ApplyPlan(ApplyPlan),
    RetireAccount(RetireAccount),
}

pub type RegisterAccount = Registration;

pub type RotateCredential = Rotation;

pub type SetPolicy = Policy;

pub type PreparePlan = PlanPreparation;

pub type PrepareProjection = ProjectionPreparation;

pub type ApprovePlan = Approval;

pub type ApplyPlan = Application;

pub type RetireAccount = Retirement;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    AccountRegistered(AccountRegistered),
    CredentialRotated(CredentialRotated),
    PolicySet(PolicySet),
    PlanPrepared(PlanPrepared),
    PlanApproved(PlanApproved),
    PlanApplied(PlanApplied),
    AccountRetired(AccountRetired),
    RequestRejected(RequestRejected),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub reason: RejectionReason,
    pub marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    ProviderNotConfigured,
    AccountUnknown,
    PlanUnknown,
    PlanNotApproved,
    CapabilityUnauthorized,
    ProviderRateLimited,
    ProviderUnavailable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

pub type CommitSequence = Integer;

pub type StateDigest = Integer;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountPolicyTable(pub Vec<AccountBinding>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountBinding {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub credential_handle: CredentialHandle,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanTable(pub Vec<StoredPlan>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredPlan {
    pub plan: Plan,
    pub approved: Boolean,
    pub marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SemaReadInput(SemaReadInput),
    SemaWriteInput(SemaWriteInput),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SemaReadOutput(SemaReadOutput),
    SemaWriteOutput(SemaWriteOutput),
}

impl AccountPolicyTable {
    pub fn new(payload: Vec<AccountBinding>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<AccountBinding> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<AccountBinding> {
        self.0
    }
}

impl From<Vec<AccountBinding>> for AccountPolicyTable {
    fn from(payload: Vec<AccountBinding>) -> Self {
        Self::new(payload)
    }
}

impl PlanTable {
    pub fn new(payload: Vec<StoredPlan>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<StoredPlan> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<StoredPlan> {
        self.0
    }
}

impl From<Vec<StoredPlan>> for PlanTable {
    fn from(payload: Vec<StoredPlan>) -> Self {
        Self::new(payload)
    }
}

impl SemaReadInput {
    pub fn observe(payload: Observe) -> Self {
        Self::Observe(payload)
    }

    pub fn observe_plan(payload: ObservePlan) -> Self {
        Self::ObservePlan(payload)
    }

    pub fn validate(payload: Validate) -> Self {
        Self::Validate(payload)
    }
}

impl SemaReadOutput {
    pub fn observed(payload: Observed) -> Self {
        Self::Observed(payload)
    }

    pub fn validated(payload: Validated) -> Self {
        Self::Validated(payload)
    }

    pub fn plan_observed(payload: PlanObserved) -> Self {
        Self::PlanObserved(payload)
    }

    pub fn missed(payload: Missed) -> Self {
        Self::Missed(payload)
    }
}

impl SemaWriteInput {
    pub fn register_account(payload: RegisterAccount) -> Self {
        Self::RegisterAccount(payload)
    }

    pub fn rotate_credential(payload: RotateCredential) -> Self {
        Self::RotateCredential(payload)
    }

    pub fn set_policy(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }

    pub fn prepare_plan(payload: PreparePlan) -> Self {
        Self::PreparePlan(payload)
    }

    pub fn prepare_projection(payload: PrepareProjection) -> Self {
        Self::PrepareProjection(payload)
    }

    pub fn approve_plan(payload: ApprovePlan) -> Self {
        Self::ApprovePlan(payload)
    }

    pub fn apply_plan(payload: ApplyPlan) -> Self {
        Self::ApplyPlan(payload)
    }

    pub fn retire_account(payload: RetireAccount) -> Self {
        Self::RetireAccount(payload)
    }
}

impl SemaWriteOutput {
    pub fn account_registered(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }

    pub fn credential_rotated(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }

    pub fn policy_set(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }

    pub fn plan_prepared(payload: PlanPrepared) -> Self {
        Self::PlanPrepared(payload)
    }

    pub fn plan_approved(payload: PlanApproved) -> Self {
        Self::PlanApproved(payload)
    }

    pub fn plan_applied(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }

    pub fn account_retired(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }

    pub fn request_rejected(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

impl Input {
    pub fn sema_read_input(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }

    pub fn sema_write_input(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

impl Output {
    pub fn sema_read_output(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }

    pub fn sema_write_output(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

impl From<Observed> for SemaReadOutput {
    fn from(payload: Observed) -> Self {
        Self::Observed(payload)
    }
}

impl From<Validated> for SemaReadOutput {
    fn from(payload: Validated) -> Self {
        Self::Validated(payload)
    }
}

impl From<AccountRegistered> for SemaWriteOutput {
    fn from(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }
}

impl From<CredentialRotated> for SemaWriteOutput {
    fn from(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }
}

impl From<PolicySet> for SemaWriteOutput {
    fn from(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
}

impl From<PlanPrepared> for SemaWriteOutput {
    fn from(payload: PlanPrepared) -> Self {
        Self::PlanPrepared(payload)
    }
}

impl From<PlanApproved> for SemaWriteOutput {
    fn from(payload: PlanApproved) -> Self {
        Self::PlanApproved(payload)
    }
}

impl From<PlanApplied> for SemaWriteOutput {
    fn from(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

impl From<AccountRetired> for SemaWriteOutput {
    fn from(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }
}

impl From<RequestRejected> for SemaWriteOutput {
    fn from(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

impl From<SemaReadInput> for Input {
    fn from(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
}

impl From<SemaWriteInput> for Input {
    fn from(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

impl From<SemaReadOutput> for Output {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
}

impl From<SemaWriteOutput> for Output {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[cfg(feature = "nota-text")]
impl SemaReadInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaReadOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaWriteInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaWriteOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl StateMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AccountPolicyTable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AccountBinding {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PlanTable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl StoredPlan {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_SEMA_READ_INPUT: u64 = 0x0000000000000000;
    pub const INPUT_SEMA_WRITE_INPUT: u64 = 0x0001000000000000;
    pub const OUTPUT_SEMA_READ_OUTPUT: u64 = 0x0100000000000000;
    pub const OUTPUT_SEMA_WRITE_OUTPUT: u64 = 0x0101000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    SemaReadInput,
    SemaWriteInput,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    SemaReadOutput,
    SemaWriteOutput,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::SemaReadInput(_) => InputRoute::SemaReadInput,
            Self::SemaWriteInput(_) => InputRoute::SemaWriteInput,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::SemaReadInput(_) => short_header::INPUT_SEMA_READ_INPUT,
            Self::SemaWriteInput(_) => short_header::INPUT_SEMA_WRITE_INPUT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_SEMA_READ_INPUT => Ok(InputRoute::SemaReadInput),
            short_header::INPUT_SEMA_WRITE_INPUT => Ok(InputRoute::SemaWriteInput),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SemaReadOutput(_) => OutputRoute::SemaReadOutput,
            Self::SemaWriteOutput(_) => OutputRoute::SemaWriteOutput,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::SemaReadOutput(_) => short_header::OUTPUT_SEMA_READ_OUTPUT,
            Self::SemaWriteOutput(_) => short_header::OUTPUT_SEMA_WRITE_OUTPUT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SEMA_READ_OUTPUT => Ok(OutputRoute::SemaReadOutput),
            short_header::OUTPUT_SEMA_WRITE_OUTPUT => Ok(OutputRoute::SemaWriteOutput),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaReadInputRoute {
    Observe,
    ObservePlan,
    Validate,
}

impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::Observe(_) => SemaReadInputRoute::Observe,
            Self::ObservePlan(_) => SemaReadInputRoute::ObservePlan,
            Self::Validate(_) => SemaReadInputRoute::Validate,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaReadOutputRoute {
    Observed,
    Validated,
    PlanObserved,
    Missed,
}

impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::Observed(_) => SemaReadOutputRoute::Observed,
            Self::Validated(_) => SemaReadOutputRoute::Validated,
            Self::PlanObserved(_) => SemaReadOutputRoute::PlanObserved,
            Self::Missed(_) => SemaReadOutputRoute::Missed,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaWriteInputRoute {
    RegisterAccount,
    RotateCredential,
    SetPolicy,
    PreparePlan,
    PrepareProjection,
    ApprovePlan,
    ApplyPlan,
    RetireAccount,
}

impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::RegisterAccount(_) => SemaWriteInputRoute::RegisterAccount,
            Self::RotateCredential(_) => SemaWriteInputRoute::RotateCredential,
            Self::SetPolicy(_) => SemaWriteInputRoute::SetPolicy,
            Self::PreparePlan(_) => SemaWriteInputRoute::PreparePlan,
            Self::PrepareProjection(_) => SemaWriteInputRoute::PrepareProjection,
            Self::ApprovePlan(_) => SemaWriteInputRoute::ApprovePlan,
            Self::ApplyPlan(_) => SemaWriteInputRoute::ApplyPlan,
            Self::RetireAccount(_) => SemaWriteInputRoute::RetireAccount,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaWriteOutputRoute {
    AccountRegistered,
    CredentialRotated,
    PolicySet,
    PlanPrepared,
    PlanApproved,
    PlanApplied,
    AccountRetired,
    RequestRejected,
}

impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::AccountRegistered(_) => SemaWriteOutputRoute::AccountRegistered,
            Self::CredentialRotated(_) => SemaWriteOutputRoute::CredentialRotated,
            Self::PolicySet(_) => SemaWriteOutputRoute::PolicySet,
            Self::PlanPrepared(_) => SemaWriteOutputRoute::PlanPrepared,
            Self::PlanApproved(_) => SemaWriteOutputRoute::PlanApproved,
            Self::PlanApplied(_) => SemaWriteOutputRoute::PlanApplied,
            Self::AccountRetired(_) => SemaWriteOutputRoute::AccountRetired,
            Self::RequestRejected(_) => SemaWriteOutputRoute::RequestRejected,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}

impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => match route {
                SemaWriteInputRoute::RegisterAccount => "SemaWriteInputRegisterAccount",
                SemaWriteInputRoute::RotateCredential => "SemaWriteInputRotateCredential",
                SemaWriteInputRoute::SetPolicy => "SemaWriteInputSetPolicy",
                SemaWriteInputRoute::PreparePlan => "SemaWriteInputPreparePlan",
                SemaWriteInputRoute::PrepareProjection => "SemaWriteInputPrepareProjection",
                SemaWriteInputRoute::ApprovePlan => "SemaWriteInputApprovePlan",
                SemaWriteInputRoute::ApplyPlan => "SemaWriteInputApplyPlan",
                SemaWriteInputRoute::RetireAccount => "SemaWriteInputRetireAccount",
            },
            Self::ReadInput(route) => match route {
                SemaReadInputRoute::Observe => "SemaReadInputObserve",
                SemaReadInputRoute::ObservePlan => "SemaReadInputObservePlan",
                SemaReadInputRoute::Validate => "SemaReadInputValidate",
            },
            Self::WriteOutput(route) => match route {
                SemaWriteOutputRoute::AccountRegistered => "SemaWriteOutputAccountRegistered",
                SemaWriteOutputRoute::CredentialRotated => "SemaWriteOutputCredentialRotated",
                SemaWriteOutputRoute::PolicySet => "SemaWriteOutputPolicySet",
                SemaWriteOutputRoute::PlanPrepared => "SemaWriteOutputPlanPrepared",
                SemaWriteOutputRoute::PlanApproved => "SemaWriteOutputPlanApproved",
                SemaWriteOutputRoute::PlanApplied => "SemaWriteOutputPlanApplied",
                SemaWriteOutputRoute::AccountRetired => "SemaWriteOutputAccountRetired",
                SemaWriteOutputRoute::RequestRejected => "SemaWriteOutputRequestRejected",
            },
            Self::ReadOutput(route) => match route {
                SemaReadOutputRoute::Observed => "SemaReadOutputObserved",
                SemaReadOutputRoute::Validated => "SemaReadOutputValidated",
                SemaReadOutputRoute::PlanObserved => "SemaReadOutputPlanObserved",
                SemaReadOutputRoute::Missed => "SemaReadOutputMissed",
            },
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectName {
    Sema(SemaObjectName),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct TraceEvent(pub ObjectName);

impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}

impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }

    pub fn object_name(&self) -> ObjectName {
        self.0
    }

    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}

impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => write!(formatter, "actor resource busy: {message}"),
            Self::ConfigurationInvalid(message) => write!(formatter, "actor configuration invalid: {message}"),
        }
    }
}

impl std::error::Error for ActorStartFailure {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}

impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => write!(formatter, "actor resource locked: {message}"),
            Self::ChildStillRunning(message) => write!(formatter, "actor child still running: {message}"),
        }
    }
}

impl std::error::Error for ActorStopFailure {}

pub trait SemaEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }

    fn apply_inner(&mut self, input: sema::Sema<sema::WriteInput>) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(&self, input: sema::Sema<sema::ReadInput>) -> sema::Sema<sema::ReadOutput>;

    fn apply(&mut self, input: sema::Sema<sema::WriteInput>) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }

    fn observe(&self, input: sema::Sema<sema::ReadInput>) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
