// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_cloud::schema::lib::Observation as Observation;
pub use signal_cloud::schema::lib::PlanQuery as PlanQuery;
pub use signal_cloud::schema::lib::Validation as Validation;
pub use signal_cloud::schema::lib::Observed as Observed;
pub use signal_cloud::schema::lib::Validated as Validated;
pub use signal_cloud::schema::lib::PlanResult as PlanResult;
pub use meta_signal_cloud::schema::lib::Registration as Registration;
pub use meta_signal_cloud::schema::lib::Rotation as Rotation;
pub use meta_signal_cloud::schema::lib::Policy as Policy;
pub use meta_signal_cloud::schema::lib::PlanPreparation as PlanPreparation;
pub use meta_signal_cloud::schema::lib::ProjectionPreparation as ProjectionPreparation;
pub use meta_signal_cloud::schema::lib::Approval as Approval;
pub use meta_signal_cloud::schema::lib::Application as Application;
pub use meta_signal_cloud::schema::lib::Retirement as Retirement;
pub use meta_signal_cloud::schema::lib::AccountRegistered as AccountRegistered;
pub use meta_signal_cloud::schema::lib::CredentialRotated as CredentialRotated;
pub use meta_signal_cloud::schema::lib::PolicySet as PolicySet;
pub use meta_signal_cloud::schema::lib::PlanPrepared as PlanPrepared;
pub use meta_signal_cloud::schema::lib::PlanApproved as PlanApproved;
pub use meta_signal_cloud::schema::lib::PlanApplied as PlanApplied;
pub use meta_signal_cloud::schema::lib::AccountRetired as AccountRetired;
pub use meta_signal_cloud::schema::lib::RequestRejected as RequestRejected;
pub use meta_signal_cloud::schema::lib::Plan as Plan;
pub use signal_cloud::schema::lib::Provider as Provider;
pub use signal_cloud::schema::lib::ProviderAccount as ProviderAccount;
pub use meta_signal_cloud::schema::lib::CredentialHandle as CredentialHandle;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadInput {
    Observe(Observe),
    ObservePlan(ObservePlan),
    Validate(Validate),
}

pub type Observe = Observation;

pub type ObservePlan = PlanQuery;

pub type Validate = Validation;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadOutput {
    Observed,
    Validated,
    PlanObserved(PlanObserved),
    Missed(Missed),
}

pub type PlanObserved = PlanResult;

pub type Missed = RejectionReport;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteInput {
    RegisterAccount(RegisterAccount),
    RotateCredential(RotateCredential),
    SetPolicy(SetPolicy),
    PreparePlan(PreparePlan),
    PrepareProjection(PrepareProjection),
    ApprovePlan(ApprovePlan),
    ApplyPlan(ApplyPlan),
    RetireAccount(RetireAccount),
}

pub type RegisterAccount = Registration;

pub type RotateCredential = Rotation;

pub type SetPolicy = Policy;

pub type PreparePlan = PlanPreparation;

pub type PrepareProjection = ProjectionPreparation;

pub type ApprovePlan = Approval;

pub type ApplyPlan = Application;

pub type RetireAccount = Retirement;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteOutput {
    AccountRegistered,
    CredentialRotated,
    PolicySet,
    PlanPrepared,
    PlanApproved,
    PlanApplied,
    AccountRetired,
    RequestRejected,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub reason: RejectionReason,
    pub marker: StateMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    ProviderNotConfigured,
    AccountUnknown,
    PlanUnknown,
    PlanNotApproved,
    CapabilityUnauthorized,
    ProviderRateLimited,
    ProviderUnavailable,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

pub type CommitSequence = Integer;

pub type StateDigest = Integer;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountPolicyTable(pub Vec<AccountBinding>);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountBinding {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub credential_handle: CredentialHandle,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanTable(pub Vec<StoredPlan>);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredPlan {
    pub plan: Plan,
    pub approved: Boolean,
    pub marker: StateMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    ReadInput(ReadInput),
    WriteInput(WriteInput),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReadOutput(ReadOutput),
    WriteOutput(WriteOutput),
}

impl AccountPolicyTable {
    pub fn new(payload: Vec<AccountBinding>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<AccountBinding> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<AccountBinding> {
        self.0
    }
}

impl From<Vec<AccountBinding>> for AccountPolicyTable {
    fn from(payload: Vec<AccountBinding>) -> Self {
        Self::new(payload)
    }
}

impl PlanTable {
    pub fn new(payload: Vec<StoredPlan>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<StoredPlan> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<StoredPlan> {
        self.0
    }
}

impl From<Vec<StoredPlan>> for PlanTable {
    fn from(payload: Vec<StoredPlan>) -> Self {
        Self::new(payload)
    }
}

impl ReadInput {
    pub fn observe(payload: Observe) -> Self {
        Self::Observe(payload)
    }

    pub fn observe_plan(payload: ObservePlan) -> Self {
        Self::ObservePlan(payload)
    }

    pub fn validate(payload: Validate) -> Self {
        Self::Validate(payload)
    }
}

impl ReadOutput {
    pub fn plan_observed(payload: PlanObserved) -> Self {
        Self::PlanObserved(payload)
    }

    pub fn missed(payload: Missed) -> Self {
        Self::Missed(payload)
    }
}

impl WriteInput {
    pub fn register_account(payload: RegisterAccount) -> Self {
        Self::RegisterAccount(payload)
    }

    pub fn rotate_credential(payload: RotateCredential) -> Self {
        Self::RotateCredential(payload)
    }

    pub fn set_policy(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }

    pub fn prepare_plan(payload: PreparePlan) -> Self {
        Self::PreparePlan(payload)
    }

    pub fn prepare_projection(payload: PrepareProjection) -> Self {
        Self::PrepareProjection(payload)
    }

    pub fn approve_plan(payload: ApprovePlan) -> Self {
        Self::ApprovePlan(payload)
    }

    pub fn apply_plan(payload: ApplyPlan) -> Self {
        Self::ApplyPlan(payload)
    }

    pub fn retire_account(payload: RetireAccount) -> Self {
        Self::RetireAccount(payload)
    }
}

impl Input {
    pub fn read_input(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }

    pub fn write_input(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

impl Output {
    pub fn read_output(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }

    pub fn write_output(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

impl From<ReadInput> for Input {
    fn from(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

impl From<WriteInput> for Input {
    fn from(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

impl From<ReadOutput> for Output {
    fn from(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

impl From<WriteOutput> for Output {
    fn from(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}



pub mod short_header {
    pub const INPUT_READ_INPUT: u64 = 0x0000000000000000;
    pub const INPUT_WRITE_INPUT: u64 = 0x0001000000000000;
    pub const OUTPUT_READ_OUTPUT: u64 = 0x0100000000000000;
    pub const OUTPUT_WRITE_OUTPUT: u64 = 0x0101000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    ReadInput,
    WriteInput,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    ReadOutput,
    WriteOutput,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::ReadInput(_) => InputRoute::ReadInput,
            Self::WriteInput(_) => InputRoute::WriteInput,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::ReadInput(_) => short_header::INPUT_READ_INPUT,
            Self::WriteInput(_) => short_header::INPUT_WRITE_INPUT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_READ_INPUT => Ok(InputRoute::ReadInput),
            short_header::INPUT_WRITE_INPUT => Ok(InputRoute::WriteInput),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::ReadOutput(_) => OutputRoute::ReadOutput,
            Self::WriteOutput(_) => OutputRoute::WriteOutput,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::ReadOutput(_) => short_header::OUTPUT_READ_OUTPUT,
            Self::WriteOutput(_) => short_header::OUTPUT_WRITE_OUTPUT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_READ_OUTPUT => Ok(OutputRoute::ReadOutput),
            short_header::OUTPUT_WRITE_OUTPUT => Ok(OutputRoute::WriteOutput),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
