// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_cloud::schema::lib::Observation as Observation;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::PlanQuery as PlanQuery;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::Validation as Validation;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::Observed as Observed;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::Validated as Validated;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::PlanResult as PlanResult;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Registration as Registration;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Rotation as Rotation;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Policy as Policy;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::PlanPreparation as PlanPreparation;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::ProjectionPreparation as ProjectionPreparation;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Approval as Approval;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Application as Application;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Retirement as Retirement;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::AccountRegistered as AccountRegistered;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::CredentialRotated as CredentialRotated;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::PolicySet as PolicySet;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::PlanPrepared as PlanPrepared;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::PlanApproved as PlanApproved;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::PlanApplied as PlanApplied;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::AccountRetired as AccountRetired;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::RequestRejected as RequestRejected;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::Plan as Plan;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::Provider as Provider;
#[rustfmt::skip]
pub use signal_cloud::schema::lib::ProviderAccount as ProviderAccount;
#[rustfmt::skip]
pub use meta_signal_cloud::schema::lib::CredentialHandle as CredentialHandle;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    Observe(Observe),
    ObservePlan(ObservePlan),
    Validate(Validate),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Observe(Observation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservePlan(PlanQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validate(Validation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    Observed(Observed),
    Validated(Validated),
    PlanObserved(PlanObserved),
    Missed(Missed),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanObserved(PlanResult);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Missed(RejectionReport);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    RegisterAccount(RegisterAccount),
    RotateCredential(RotateCredential),
    SetPolicy(SetPolicy),
    PreparePlan(PreparePlan),
    PrepareProjection(PrepareProjection),
    ApprovePlan(ApprovePlan),
    ApplyPlan(ApplyPlan),
    RetireAccount(RetireAccount),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterAccount(Registration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RotateCredential(Rotation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SetPolicy(Policy);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PreparePlan(PlanPreparation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PrepareProjection(ProjectionPreparation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApprovePlan(Approval);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplyPlan(Application);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireAccount(Retirement);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    AccountRegistered(AccountRegistered),
    CredentialRotated(CredentialRotated),
    PolicySet(PolicySet),
    PlanPrepared(PlanPrepared),
    PlanApproved(PlanApproved),
    PlanApplied(PlanApplied),
    AccountRetired(AccountRetired),
    RequestRejected(RequestRejected),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub reason: RejectionReason,
    pub marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    ProviderNotConfigured,
    AccountUnknown,
    PlanUnknown,
    PlanNotApproved,
    CapabilityUnauthorized,
    ProviderRateLimited,
    ProviderUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDigest(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountPolicyTable(Vec<AccountBinding>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountBinding {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub credential_handle: CredentialHandle,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanTable(Vec<StoredPlan>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredPlan {
    pub plan: Plan,
    pub approved: Boolean,
    pub marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SemaReadInput(SemaReadInput),
    SemaWriteInput(SemaWriteInput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SemaReadOutput(SemaReadOutput),
    SemaWriteOutput(SemaWriteOutput),
}

#[rustfmt::skip]
impl Observe {
    pub fn new(payload: Observation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Observation {
        &self.0
    }
    pub fn into_payload(self) -> Observation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Observation> for Observe {
    fn from(payload: Observation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservePlan {
    pub fn new(payload: PlanQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanQuery {
        &self.0
    }
    pub fn into_payload(self) -> PlanQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanQuery> for ObservePlan {
    fn from(payload: PlanQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validate {
    pub fn new(payload: Validation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Validation {
        &self.0
    }
    pub fn into_payload(self) -> Validation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Validation> for Validate {
    fn from(payload: Validation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PlanObserved {
    pub fn new(payload: PlanResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanResult {
        &self.0
    }
    pub fn into_payload(self) -> PlanResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanResult> for PlanObserved {
    fn from(payload: PlanResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Missed {
    pub fn new(payload: RejectionReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectionReport {
        &self.0
    }
    pub fn into_payload(self) -> RejectionReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectionReport> for Missed {
    fn from(payload: RejectionReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegisterAccount {
    pub fn new(payload: Registration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Registration {
        &self.0
    }
    pub fn into_payload(self) -> Registration {
        self.0
    }
}
#[rustfmt::skip]
impl From<Registration> for RegisterAccount {
    fn from(payload: Registration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RotateCredential {
    pub fn new(payload: Rotation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Rotation {
        &self.0
    }
    pub fn into_payload(self) -> Rotation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Rotation> for RotateCredential {
    fn from(payload: Rotation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SetPolicy {
    pub fn new(payload: Policy) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Policy {
        &self.0
    }
    pub fn into_payload(self) -> Policy {
        self.0
    }
}
#[rustfmt::skip]
impl From<Policy> for SetPolicy {
    fn from(payload: Policy) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PreparePlan {
    pub fn new(payload: PlanPreparation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanPreparation {
        &self.0
    }
    pub fn into_payload(self) -> PlanPreparation {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanPreparation> for PreparePlan {
    fn from(payload: PlanPreparation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PrepareProjection {
    pub fn new(payload: ProjectionPreparation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProjectionPreparation {
        &self.0
    }
    pub fn into_payload(self) -> ProjectionPreparation {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProjectionPreparation> for PrepareProjection {
    fn from(payload: ProjectionPreparation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApprovePlan {
    pub fn new(payload: Approval) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Approval {
        &self.0
    }
    pub fn into_payload(self) -> Approval {
        self.0
    }
}
#[rustfmt::skip]
impl From<Approval> for ApprovePlan {
    fn from(payload: Approval) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApplyPlan {
    pub fn new(payload: Application) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Application {
        &self.0
    }
    pub fn into_payload(self) -> Application {
        self.0
    }
}
#[rustfmt::skip]
impl From<Application> for ApplyPlan {
    fn from(payload: Application) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireAccount {
    pub fn new(payload: Retirement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Retirement {
        &self.0
    }
    pub fn into_payload(self) -> Retirement {
        self.0
    }
}
#[rustfmt::skip]
impl From<Retirement> for RetireAccount {
    fn from(payload: Retirement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommitSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CommitSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateDigest {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for StateDigest {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AccountPolicyTable {
    pub fn new(payload: Vec<AccountBinding>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<AccountBinding> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<AccountBinding> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<AccountBinding>> for AccountPolicyTable {
    fn from(payload: Vec<AccountBinding>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PlanTable {
    pub fn new(payload: Vec<StoredPlan>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<StoredPlan> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<StoredPlan> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<StoredPlan>> for PlanTable {
    fn from(payload: Vec<StoredPlan>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn observe(payload: Observation) -> Self {
        Self::Observe(Observe::new(payload))
    }
    pub fn observe_plan(payload: PlanQuery) -> Self {
        Self::ObservePlan(ObservePlan::new(payload))
    }
    pub fn validate(payload: Validation) -> Self {
        Self::Validate(Validate::new(payload))
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn observed(payload: Observed) -> Self {
        Self::Observed(payload)
    }
    pub fn validated(payload: Validated) -> Self {
        Self::Validated(payload)
    }
    pub fn plan_observed(payload: PlanResult) -> Self {
        Self::PlanObserved(PlanObserved::new(payload))
    }
    pub fn missed(payload: RejectionReport) -> Self {
        Self::Missed(Missed::new(payload))
    }
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn register_account(payload: Registration) -> Self {
        Self::RegisterAccount(RegisterAccount::new(payload))
    }
    pub fn rotate_credential(payload: Rotation) -> Self {
        Self::RotateCredential(RotateCredential::new(payload))
    }
    pub fn set_policy(payload: Policy) -> Self {
        Self::SetPolicy(SetPolicy::new(payload))
    }
    pub fn prepare_plan(payload: PlanPreparation) -> Self {
        Self::PreparePlan(PreparePlan::new(payload))
    }
    pub fn prepare_projection(payload: ProjectionPreparation) -> Self {
        Self::PrepareProjection(PrepareProjection::new(payload))
    }
    pub fn approve_plan(payload: Approval) -> Self {
        Self::ApprovePlan(ApprovePlan::new(payload))
    }
    pub fn apply_plan(payload: Application) -> Self {
        Self::ApplyPlan(ApplyPlan::new(payload))
    }
    pub fn retire_account(payload: Retirement) -> Self {
        Self::RetireAccount(RetireAccount::new(payload))
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn account_registered(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }
    pub fn credential_rotated(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }
    pub fn policy_set(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
    pub fn plan_prepared(payload: PlanPrepared) -> Self {
        Self::PlanPrepared(payload)
    }
    pub fn plan_approved(payload: PlanApproved) -> Self {
        Self::PlanApproved(payload)
    }
    pub fn plan_applied(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
    pub fn account_retired(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }
    pub fn request_rejected(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn sema_read_input(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
    pub fn sema_write_input(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn sema_read_output(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
    pub fn sema_write_output(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<Observe> for SemaReadInput {
    fn from(payload: Observe) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<ObservePlan> for SemaReadInput {
    fn from(payload: ObservePlan) -> Self {
        Self::ObservePlan(payload)
    }
}

#[rustfmt::skip]
impl From<Validate> for SemaReadInput {
    fn from(payload: Validate) -> Self {
        Self::Validate(payload)
    }
}

#[rustfmt::skip]
impl From<Observed> for SemaReadOutput {
    fn from(payload: Observed) -> Self {
        Self::Observed(payload)
    }
}

#[rustfmt::skip]
impl From<Validated> for SemaReadOutput {
    fn from(payload: Validated) -> Self {
        Self::Validated(payload)
    }
}

#[rustfmt::skip]
impl From<PlanObserved> for SemaReadOutput {
    fn from(payload: PlanObserved) -> Self {
        Self::PlanObserved(payload)
    }
}

#[rustfmt::skip]
impl From<Missed> for SemaReadOutput {
    fn from(payload: Missed) -> Self {
        Self::Missed(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterAccount> for SemaWriteInput {
    fn from(payload: RegisterAccount) -> Self {
        Self::RegisterAccount(payload)
    }
}

#[rustfmt::skip]
impl From<RotateCredential> for SemaWriteInput {
    fn from(payload: RotateCredential) -> Self {
        Self::RotateCredential(payload)
    }
}

#[rustfmt::skip]
impl From<SetPolicy> for SemaWriteInput {
    fn from(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }
}

#[rustfmt::skip]
impl From<PreparePlan> for SemaWriteInput {
    fn from(payload: PreparePlan) -> Self {
        Self::PreparePlan(payload)
    }
}

#[rustfmt::skip]
impl From<PrepareProjection> for SemaWriteInput {
    fn from(payload: PrepareProjection) -> Self {
        Self::PrepareProjection(payload)
    }
}

#[rustfmt::skip]
impl From<ApprovePlan> for SemaWriteInput {
    fn from(payload: ApprovePlan) -> Self {
        Self::ApprovePlan(payload)
    }
}

#[rustfmt::skip]
impl From<ApplyPlan> for SemaWriteInput {
    fn from(payload: ApplyPlan) -> Self {
        Self::ApplyPlan(payload)
    }
}

#[rustfmt::skip]
impl From<RetireAccount> for SemaWriteInput {
    fn from(payload: RetireAccount) -> Self {
        Self::RetireAccount(payload)
    }
}

#[rustfmt::skip]
impl From<AccountRegistered> for SemaWriteOutput {
    fn from(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<CredentialRotated> for SemaWriteOutput {
    fn from(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }
}

#[rustfmt::skip]
impl From<PolicySet> for SemaWriteOutput {
    fn from(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
}

#[rustfmt::skip]
impl From<PlanPrepared> for SemaWriteOutput {
    fn from(payload: PlanPrepared) -> Self {
        Self::PlanPrepared(payload)
    }
}

#[rustfmt::skip]
impl From<PlanApproved> for SemaWriteOutput {
    fn from(payload: PlanApproved) -> Self {
        Self::PlanApproved(payload)
    }
}

#[rustfmt::skip]
impl From<PlanApplied> for SemaWriteOutput {
    fn from(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

#[rustfmt::skip]
impl From<AccountRetired> for SemaWriteOutput {
    fn from(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }
}

#[rustfmt::skip]
impl From<RequestRejected> for SemaWriteOutput {
    fn from(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for Input {
    fn from(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteInput> for Input {
    fn from(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for Output {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for Output {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadInputRoute {
    Observe,
    ObservePlan,
    Validate,
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::Observe(_) => SemaReadInputRoute::Observe,
            Self::ObservePlan(_) => SemaReadInputRoute::ObservePlan,
            Self::Validate(_) => SemaReadInputRoute::Validate,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadOutputRoute {
    Observed,
    Validated,
    PlanObserved,
    Missed,
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::Observed(_) => SemaReadOutputRoute::Observed,
            Self::Validated(_) => SemaReadOutputRoute::Validated,
            Self::PlanObserved(_) => SemaReadOutputRoute::PlanObserved,
            Self::Missed(_) => SemaReadOutputRoute::Missed,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteInputRoute {
    RegisterAccount,
    RotateCredential,
    SetPolicy,
    PreparePlan,
    PrepareProjection,
    ApprovePlan,
    ApplyPlan,
    RetireAccount,
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::RegisterAccount(_) => SemaWriteInputRoute::RegisterAccount,
            Self::RotateCredential(_) => SemaWriteInputRoute::RotateCredential,
            Self::SetPolicy(_) => SemaWriteInputRoute::SetPolicy,
            Self::PreparePlan(_) => SemaWriteInputRoute::PreparePlan,
            Self::PrepareProjection(_) => SemaWriteInputRoute::PrepareProjection,
            Self::ApprovePlan(_) => SemaWriteInputRoute::ApprovePlan,
            Self::ApplyPlan(_) => SemaWriteInputRoute::ApplyPlan,
            Self::RetireAccount(_) => SemaWriteInputRoute::RetireAccount,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteOutputRoute {
    AccountRegistered,
    CredentialRotated,
    PolicySet,
    PlanPrepared,
    PlanApproved,
    PlanApplied,
    AccountRetired,
    RequestRejected,
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::AccountRegistered(_) => SemaWriteOutputRoute::AccountRegistered,
            Self::CredentialRotated(_) => SemaWriteOutputRoute::CredentialRotated,
            Self::PolicySet(_) => SemaWriteOutputRoute::PolicySet,
            Self::PlanPrepared(_) => SemaWriteOutputRoute::PlanPrepared,
            Self::PlanApproved(_) => SemaWriteOutputRoute::PlanApproved,
            Self::PlanApplied(_) => SemaWriteOutputRoute::PlanApplied,
            Self::AccountRetired(_) => SemaWriteOutputRoute::AccountRetired,
            Self::RequestRejected(_) => SemaWriteOutputRoute::RequestRejected,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    SemaWriteInputRoute::RegisterAccount => {
                        "SemaWriteInputRegisterAccount"
                    }
                    SemaWriteInputRoute::RotateCredential => {
                        "SemaWriteInputRotateCredential"
                    }
                    SemaWriteInputRoute::SetPolicy => "SemaWriteInputSetPolicy",
                    SemaWriteInputRoute::PreparePlan => "SemaWriteInputPreparePlan",
                    SemaWriteInputRoute::PrepareProjection => {
                        "SemaWriteInputPrepareProjection"
                    }
                    SemaWriteInputRoute::ApprovePlan => "SemaWriteInputApprovePlan",
                    SemaWriteInputRoute::ApplyPlan => "SemaWriteInputApplyPlan",
                    SemaWriteInputRoute::RetireAccount => "SemaWriteInputRetireAccount",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    SemaReadInputRoute::Observe => "SemaReadInputObserve",
                    SemaReadInputRoute::ObservePlan => "SemaReadInputObservePlan",
                    SemaReadInputRoute::Validate => "SemaReadInputValidate",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    SemaWriteOutputRoute::AccountRegistered => {
                        "SemaWriteOutputAccountRegistered"
                    }
                    SemaWriteOutputRoute::CredentialRotated => {
                        "SemaWriteOutputCredentialRotated"
                    }
                    SemaWriteOutputRoute::PolicySet => "SemaWriteOutputPolicySet",
                    SemaWriteOutputRoute::PlanPrepared => "SemaWriteOutputPlanPrepared",
                    SemaWriteOutputRoute::PlanApproved => "SemaWriteOutputPlanApproved",
                    SemaWriteOutputRoute::PlanApplied => "SemaWriteOutputPlanApplied",
                    SemaWriteOutputRoute::AccountRetired => {
                        "SemaWriteOutputAccountRetired"
                    }
                    SemaWriteOutputRoute::RequestRejected => {
                        "SemaWriteOutputRequestRejected"
                    }
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    SemaReadOutputRoute::Observed => "SemaReadOutputObserved",
                    SemaReadOutputRoute::Validated => "SemaReadOutputValidated",
                    SemaReadOutputRoute::PlanObserved => "SemaReadOutputPlanObserved",
                    SemaReadOutputRoute::Missed => "SemaReadOutputMissed",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for SemaWriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for SemaWriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for SemaReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for SemaReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
